### ISSUE TITLE
Linking error during build: /usr/bin/ld: cannot find -lglog::glog

### ISSUE THREAD

**Issue by TakShimoda** [mit-acl/dpgo_ros#3] opened 2023-08-28 20:09 UTC
Hello, I'm on ubuntu 20.04 with ROS noetic, trying to build another library, Kimera-Multi from https://github.com/MIT-SPARK/Kimera-Multi. It's a ROS package and in its dependencies, it needs dpgo_ros among others in the catkin workspace, but I get an error related to a linking issue with glog

```
> [ 91%]  [32m [1mLinking CXX shared library /home/glenn/catkin_ws/devel/.private/dpgo_ros/lib/libdpgo_ros.so [0m
> /usr/bin/ld: cannot find -lglog::glog
> collect2: error: ld returned 1 exit status
> make[2]: *** [CMakeFiles/dpgo_ros.dir/build.make:141: /home/glenn/catkin_ws/devel/.private/dpgo_ros/lib/libdpgo_ros.so] Error 1
> make[1]: *** [CMakeFiles/Makefile2:468: CMakeFiles/dpgo_ros.dir/all] Error 2
> make: *** [Makefile:141: all] Error 2
```

I have installed glog with `sudo apt install libgoogle-glog-dev`, and I have installed the original [dpgo library](https://github.com/mit-acl/dpgo) successfully in a non-catkin workspace, by adding the line `set(CMAKE_PREFIX_PATH "/usr/include/glog" $ {CMAKE_PREFIX_PATH})` to the top-level CMakeLists.txt. 

However, I tried the same thing to the dpgo repository that's cloned into the catkin workspace as a dependency of dpgo_ros, but I get the error as mentioned above

I also tried installing glog from source and tried the [recommendation from glog](https://github.com/google/glog#consuming-glog-in-a-cmake-project) on how to use it in a cmake project by adding glog::glog as a library to link to in [the target_link_libraries command of dpgo](https://github.com/mit-acl/dpgo/blob/main/CMakeLists.txt#L94-L100) but the same issue persists.

The contents of the the file /home/glenn/catkin_ws/build/dpgo_ros/CMakeFiles/link.txt shows:

`/usr/bin/c++ -fPIC  -Wall -std=c++17 -march=native -pthread -O3 -g  -shared -Wl,-soname,libdpgo_ros.so -o /home/glenn/catkin_ws/devel/.private/dpgo_ros/lib/libdpgo_ros.so CMakeFiles/dpgo_ros.dir/src/PGOAgentROS.cpp.o CMakeFiles/dpgo_ros.dir/src/utils.cpp.o  -Wl,-rpath,/home/glenn/catkin_ws/devel/.private/pose_graph_tools/lib:/opt/ros/noetic/lib:/home/glenn/catkin_ws/devel/lib /home/glenn/catkin_ws/devel/.private/pose_graph_tools/lib/libpose_graph_tools.so /opt/ros/noetic/lib/libinteractive_markers.so /opt/ros/noetic/lib/libtf2_ros.so /opt/ros/noetic/lib/libactionlib.so /opt/ros/noetic/lib/libmessage_filters.so /opt/ros/noetic/lib/libroscpp.so -lpthread /usr/lib/x86_64-linux-gnu/libboost_chrono.so.1.71.0 /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.71.0 /opt/ros/noetic/lib/librosconsole.so /opt/ros/noetic/lib/librosconsole_log4cxx.so /opt/ros/noetic/lib/librosconsole_backend_interface.so -llog4cxx /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.71.0 /opt/ros/noetic/lib/libxmlrpcpp.so /opt/ros/noetic/lib/libtf2.so /opt/ros/noetic/lib/libroscpp_serialization.so /opt/ros/noetic/lib/librostime.so /usr/lib/x86_64-linux-gnu/libboost_date_time.so.1.71.0 /opt/ros/noetic/lib/libcpp_common.so /usr/lib/x86_64-linux-gnu/libboost_system.so.1.71.0 /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.71.0 /usr/lib/x86_64-linux-gnu/libconsole_bridge.so.0.4 /home/glenn/catkin_ws/devel/lib/libDPGO.so -lpthread /home/glenn/catkin_ws/devel/lib/libroptlib.so -llapack -lblas -lm -lglog::glog -lcholmod -lamd -lcolamd -lcamd -lccolamd -lmetis -lspqr -lcholmod -lamd -lcolamd -lcamd -lccolamd -lmetis -lspqr `

so I'm getting confused where in the catkin process it tries to link to '-lglog::glog'. I tried looking in my directories and found no symbols, as I'm pretty sure it's usually a shared object library and not in the format specified above. 

**Update:** as I was writing this, I managed to get it to build by manually going to the link.txt build artifact of several packages under dpgo_ros and manually erased the lines -lglog::glog and direcly placed the path to the glog library /usr/local/lib/libglog.so.0.7.0. I don't think this is a recommended fix and maybe issues could arise when running (I have tried the simple demo and there doesn't seem to be any issues.), so I was wondering if there is a better way to fix this in the cmake configuration process. 

Sorry if this is a glog issue and is irrelevant to this package (in which case I'll close the issue) as I had no issue building the original dpgo package in a non-catkin workspace, and found no such related issue in glog's github repository. 

Thank you.

**Comment by yuluntian** [comment] 2023-08-29 03:17
Hi, sorry that you encountered this issue while using the code. I am also on Ubuntu 20.04 with ROS noetic, but at the moment I'm having trouble reproducing this issue. 

From reading your message, it seems like even with standard CMake (without catkin), you had to manually tweak the CMakeList.txt (by setting `CMAKE_PREFIX_PATH`) to build the original dpgo library. This seems strange -- have you tried to build dpgo using the default CMakeList.txt? If there is an error, could you share it here?

**Comment by TakShimoda** [comment] 2023-08-29 14:48
Hello,

I successfully recreated the error and fixed the problem. Here is what I did to get the error:

1. I retried building the dpgo with just regular CMake (without Catkin) and it worked fine just as it was, without editing anything. I didn't need to add any line to help find glog.
2. I made a new catkin workspace, cloned dpgo and I successfully built it without any errors.
3. I then built the other dependencies for dpgo_ros (catkin_simple and pose_graph_tools) in the same catkin workspace without errors
4. I cloned and tried to build dpgo_ros in the same catkin workspace and got the same error I mentioned above

Here's the output of catkin build:

```
Profile:                     default
Extending:          [cached] /opt/ros/noetic
Workspace:                   /home/glenn/catkin_ws2
-----------------------------------------------------------
Build Space:        [exists] /home/glenn/catkin_ws2/build
Devel Space:        [exists] /home/glenn/catkin_ws2/devel
Install Space:      [unused] /home/glenn/catkin_ws2/install
Log Space:          [exists] /home/glenn/catkin_ws2/logs
Source Space:       [exists] /home/glenn/catkin_ws2/src
DESTDIR:            [unused] None
-----------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
-----------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-----------------------------------------------------------
Buildlisted Packages:        None
Skiplisted Packages:         None
-----------------------------------------------------------
Workspace configuration appears valid.
-----------------------------------------------------------
[build] Found 4 packages in 0.0 seconds.                                                                                                                                                                  
[build] Updating package table.                                                                                                                                                                           
Starting  >>> catkin_simple                                                                                                                                                                               
Starting  >>> dpgo                                                                                                                                                                                        
Finished  <<< dpgo                            [ 0.9 seconds ]                                                                                                                                             
Finished  <<< catkin_simple                   [ 2.2 seconds ]                                                                                                                                             
Starting  >>> pose_graph_tools                                                                                                                                                                            
Finished  <<< pose_graph_tools                [ 6.7 seconds ]                                                                                                                                             
Starting  >>> dpgo_ros                                                                                                                                                                                    
__________________________________________________________________________________________________________________________________________________________________________________________________________
Warnings   << dpgo_ros:cmake /home/glenn/catkin_ws2/logs/dpgo_ros/build.cmake.001.log                                                                                                                     
CMake Warning (dev) at CMakeLists.txt:2 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    CMAKE_PROJECT_VERSION
    CMAKE_PROJECT_VERSION_MAJOR
    CMAKE_PROJECT_VERSION_MINOR
    CMAKE_PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /opt/ros/noetic/share/catkin/cmake/test/gtest.cmake:180 (add_executable):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "test_utils" links to target "glog::glog" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  /opt/ros/noetic/share/catkin/cmake/test/gtest.cmake:89 (_catkin_add_executable_with_google_test)
  /opt/ros/noetic/share/catkin/cmake/test/gtest.cmake:37 (_catkin_add_google_test)
  CMakeLists.txt:186 (catkin_add_gtest)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:156 (add_executable):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "dpgo_ros_node" links to target "glog::glog" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:139 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "dpgo_ros" links to target "glog::glog" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:157 (add_executable):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "dpgo_ros_dataset_publisher_node" links to target "glog::glog" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

cd /home/glenn/catkin_ws2/build/dpgo_ros; catkin build --get-env dpgo_ros | catkin env -si  /usr/bin/cmake /home/glenn/catkin_ws2/src/dpgo_ros --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/glenn/catkin_ws2/devel/.private/dpgo_ros -DCMAKE_INSTALL_PREFIX=/home/glenn/catkin_ws2/install; cd -

..........................................................................................................................................................................................................
__________________________________________________________________________________________________________________________________________________________________________________________________________
Errors     << dpgo_ros:make /home/glenn/catkin_ws2/logs/dpgo_ros/build.make.000.log                                                                                                                       
/usr/bin/ld: cannot find -lglog::glog
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/dpgo_ros.dir/build.make:141: /home/glenn/catkin_ws2/devel/.private/dpgo_ros/lib/libdpgo_ros.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:468: CMakeFiles/dpgo_ros.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
cd /home/glenn/catkin_ws2/build/dpgo_ros; catkin build --get-env dpgo_ros | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -

..........................................................................................................................................................................................................
Failed     << dpgo_ros:make                   [ Exited with code 2 ]                                                                                                                                      
Failed    <<< dpgo_ros                        [ 18.1 seconds ]                                                                                                                                            
[build] Summary: 3 of 4 packages succeeded.                                                                                                                                                               
[build]   Ignored:   None.                                                                                                                                                                                
[build]   Warnings:  1 packages succeeded with warnings.                                                                                                                                                  
[build]   Abandoned: None.                                                                                                                                                                                
[build]   Failed:    1 packages failed.                                                                                                                                                                   
[build] Runtime: 27.1 seconds total.                                                                                                                                                                      
[build] Note: Workspace packages have changed, please re-source setup files to use them.
```
I noticed the error message states that targets such as ros nodes dpgo_ros and dpgo_ros_node are trying to link to glog::glog but that target cannot be found. I looked at the lines to link the nodes [here](https://github.com/mit-acl/dpgo_ros/blob/main/CMakeLists.txt#L150-L153) and [here](https://github.com/mit-acl/dpgo_ros/blob/main/CMakeLists.txt#L172-L175). I didn't know what the variable catkin_LIBRARIES contained and thought maybe it didn't find glog so I added `find_package(Glog Required)` to CMakeLists.txt of dpgo_ros and it built successfully.

**Comment by yuluntian** [comment] 2023-08-30 03:03
Hi @TakShimoda, great, thanks for the updates and for sharing the solution! Unfortunately I can't test your fix locally because I'm still having trouble to reproduce the error (I followed steps 1-4 as outlined above). But since this has been resolved, I will close this issue for now. Feel free to re-open if you need to continue the discussion at some point.

**Closed as completed by yuluntian** 2023-08-30 03:03 UTC

**Comment by LimHyungTae** [comment] 2024-08-19 23:38
I'm not sure, but `sudo apt install libgoogle-glog-dev` is not a good solution because it sometimes leads to the conflict between local glog and glog from `glog_catkin` as follows:

```
ERROR: something wrong with flag 'logtostderr' in file '/workspace/lib/glog/src/logging.cc'.  One possibility: file '/workspace/lib/glog/src/logging.cc' is being linked both statically and dynamically into this executable.
================================================================================REQUIRED process [kimera_vio_ros/kimera_vio_ros_node-2] has died!
process has died [pid 3682959, exit code 1, cmd /home/shapelim/kimera_vio_ws/devel/lib/kimera_vio_ros/kimera_vio_ros_node --use_lcd=false --vocabulary_path=/home/shapelim/kimera_vio_ws/src/Kimera-VIO/vocabulary/ORBvoc.yml --flagfile=/home/shapelim/kimera_vio_ws/src/Kimera-VIO/params/Euroc/flags/Mesher.flags --flagfile=/home/shapelim/kimera_vio_ws/src/Kimera-VIO/params/Euroc/flags/VioBackend.flags --flagfile=/home/shapelim/kimera_vio_ws/src/Kimera-VIO/params/Euroc/flags/RegularVioBackend.flags --flagfile=/home/shapelim/kimera_vio_ws/src/Kimera-VIO/params/Euroc/flags/Visualizer3D.flags --use_external_odometry=false --do_coarse_imu_camera_temporal_sync=false --do_fine_imu_camera_temporal_sync=false --lcd_no_optimize=false --lcd_no_detection=false --depth_image_mask= --logtostderr=1 --colorlogtostderr=1 --log_prefix=1 --minloglevel=0 --v=0 --log_output=false --log_euroc_gt_data=false --output_path=/home/shapelim/kimera_vio_ws/src/Kimera-VIO-ROS/output_logs/ --lcd_disable_stereo_match_depth_check=false --no_incremental_pose=false --viz_type=0 --visualize=true reinit_flag:=reinit_flag reinit_pose:=reinit_pose odometry:=odometry resiliency:=resiliency imu_bias:=imu_bias optimized_trajectory:=optimized_trajectory pose_graph:=pose_graph mesh:=mesh frontend_stats:=frontend_stats debug_mesh_img/image_raw:=debug_mesh_img/image_raw feature_tracks/image_raw:=feature_tracks/image_raw time_horizon_pointcloud:=time_horizon_pointcloud __name:=kimera_vio_ros_node __log:=/home/shapelim/.ros/log/d62b4e54-5c22-11ef-8b10-89c894c2eed9/kimera_vio_ros-kimera_vio_ros_node-2.log].
log file: /home/shapelim/.ros/log/d62b4e54-5c22-11ef-8b10-89c894c2eed9/kimera_vio_ros-kimera_vio_ros_node-2*.log
Initiating shutdown!
================================================================================
```

Instead, we have to figure out how to integrate Glog from the local workspace

**Comment by LimHyungTae** [comment] 2024-08-20 00:00
In my case, just adding a single line resolved the problem: 

```
find_package(glog REQUIRED)
```

And I guess this glog is from `glog_catkin`.
